Add authentication against signature-authentication-server
Neufund/generic-ico pull request #11
Opened 2017-06-03 22:54 UTC by Recmo

2017-06-06 21:29 UTC, banciur approved these changes
I don't see any problems here.
But let's be honest I didn't manage to go through it as thoroughly as I should.

2017-06-07 10:44 UTC, Recmo commented
I should add instructions on how to set it up for testing in the Readme.

2017-06-07 12:21 UTC, Recmo commented
@banciur  I made some significant changes, can you review again?

2017-06-07 13:03 UTC, banciur requested changes
Just small README.md fix

2017-06-07 13:03 UTC, banciur commented on README.md
> +yarn start testrpc
Correct command is `yarn testrpc`

2017-06-07 13:38 UTC, banciur approved these changes

2017-06-07 13:39 UTC, merged