Html layout (WIP)
Neufund/generic-ico pull request #16
Opened 2017-06-06 12:37 UTC by Moejoe90

Currently the file modified is Index.html with all react components removed to represent a pure html environment.

2017-06-07 10:22 UTC, recmo requested changes
Somehow `src/index.js` got reverted to an older version. I think there's something wrong in the commit history.

2017-06-07 10:22 UTC, recmo commented on .travis.yml
> +  email: false
What is this change for?

2017-06-07 10:22 UTC, recmo commented on index CPY.html
> +<!doctype html>
Spaces in file names cause all sorts of problems. It's better to use `_`.

2017-06-07 10:22 UTC, recmo commented on index CPY.html
> +    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/flexboxgrid/6.3.1/flexboxgrid.css" type="text/css">
If this was not a test file, it should either have and `integrity` attribute or be included in the source (we already have `flexbox` as a dependency)

[No action required]

2017-06-07 10:22 UTC, recmo commented on public/index.html
> +    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/flexboxgrid/6.3.1/flexboxgrid.css" type="text/css">
We should use a bundled version, the one that was added in `package.json`.

@banciur How does one include stylesheet like that? `import 'flexboxgrind';` in `index.js`?

2017-06-07 10:59 UTC, Moejoe90 commented on .travis.yml
> +  email: false
This is to disable Travis email notification, apparently you have to manually put this in the travis.yml file

2017-06-07 10:59 UTC, Moejoe90 commented on index CPY.html
> +<!doctype html>
Will take that into account

2017-06-08 08:24 UTC, Recmo commented
This PR has been superseded by others.

2017-06-08 08:24 UTC, closed without merging