Lint scss files (WIP)
Neufund/generic-ico pull request #23
Opened 2017-06-08 09:37 UTC by Recmo

2017-06-08 11:08 UTC, Recmo commented on src/styles/colors.scss
> +// sass-lint:enab
Line got cut half way

2017-06-08 14:25 UTC, banciur requested changes
Now when I'm trying to build I receive 

```
ERROR in ./~/css-loader?{"camelCase":"dashesOnly"}!./~/sass-loader/lib/loader.js!./src/components/Footer.scss
Module build failed: 
  @extend %footer;
         ^
      ".footer" failed to @extend "%footer".
The selector "%footer" was not found.
Use "@extend %footer !optional" if the extend should be able to fail.
      in /home/banciur/projects/neufund/generic-ico/src/components/Footer.scss (line 5, column 11)
 @ ./src/components/Footer.scss 4:14-134 18:2-22:4 19:20-140
```
I thought there is some problem with dependencies so I deleted `node_modules` directory and performed `yarn` command and then `yarn serve` but it didn't help

2017-06-08 14:25 UTC, banciur commented on src/components/Footer.scss
> -  composes: Montserrat from '../styles/fonts.scss';
As we talked on slack we shouldn't use `composes` feature of css-modules. Same goes for Header.scss file

2017-06-08 14:27 UTC, Recmo commented on src/components/Footer.scss
> -  composes: Montserrat from '../styles/fonts.scss';
This is an old version of the file. Are you sure you reviewed the latest version?

2017-06-08 17:07 UTC, banciur approved these changes
It is working at this moment.

2017-06-08 17:07 UTC, banciur commented on src/components/Footer.scss
> +@import '../styles/fonts';
You are missing `@import '../styles/colors';` in Footer.scss

2017-06-08 17:07 UTC, banciur commented on src/styles/colors.scss
>  .footer {
This line should look like this `%footer {`

2017-06-08 17:13 UTC, merged

2017-06-09 10:19 UTC, recmo reviewed
Bug.

2017-06-09 10:19 UTC, Recmo commented on src/components/Button.scss
> +  :hover {
Turns out this should have been `&:hover`.