WIP: Basic routing
Neufund/generic-ico pull request #7
Opened 2017-05-31 14:47 UTC by banciur

This is initial state. I think its not that interesting at this moment.
I suspend working on it to implement Link component in dapp-starter-kit and when I realized I don't know to implement more complex components and how to approach this layout problem.

What I had in mind when I was talking about next steps in routing was to enter all routes into routes.js And simple components that would look a bit like. 

```
RegisterEmail.js:
export default () => 
<div>
    Register using Email <br /> 
    <Link text="KYC" path="/kyc" />
</div>;
```

That would give us basic skeleton. I'm not sure if this would be that useful. But we would have placeholders for every element on Ola's diagram.

2017-05-31 16:26 UTC, Recmo commented on src/components/Header.js
> +    <hr />
just fyi. This stuff should be done using `<nav><ul>….` like in [this example](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nav).

2017-06-06 10:10 UTC, banciur commented
I think it's a good moment to merge those basic routes.
Those cover latest changes in flow in invision and I could start working on layouts and views.
My understanding is that this week we focus on register / login process so KYC would be last possible route user will reach. That's why I didn't add anything behind that.

2017-06-06 12:20 UTC, recmo requested changes

2017-06-06 12:20 UTC, recmo commented on src/components/Header.js
> +          <LoginLink>Login</LoginLink>
This is a user visible string and thus requires translation: `<LoginLink>{i18n('Login')}</LoginLink>`

2017-06-06 12:20 UTC, Recmo commented on src/components/PredefinedLinks.js
> +// TODO: Is it possible to rewrite this without usage of return but keeping propTypes check?
I've looked into this in the past, you can do it with an anonymous class:

```
const LinkCreator = path =>
  class extends React.PureComponent {
    static propTypes = {
      children: PropTypes.node.isRequired,
    };
    render() {
      return <Link {...props} path={path}>{children}</Link>;
    }
  };
```
… but that looks even worse than what we started with :)

I did a bit more research, it *looks* like `Object.assign` can be used in this case:

```
const LinkCreator = path =>
  Object.assign(
    ({ children, ...props }) => <Link {...props} path={path}>{children}</Link>,
    { propTypes: {
      children: PropTypes.node.isRequired
    }});
```

With this as a basis, we can make a little helper function to clean up the code:

```
const withProps = (component, propTypes, defaultProps) =>
  Object.assign(component, { propTypes, defaultProps });

const LinkCreator = path => withProps(
  ({ children, ...props }) => <Link {...props} path={path}>{children}</Link>,
  {
    children: PropTypes.node.isRequired,
  });
```

This `withProps` is kinda cute, maybe we should have it in `src/utils.js`.

2017-06-06 12:20 UTC, Recmo commented on src/views/ConfirmEmail.js
> +</div>);
This is missing `i18n` functions.

2017-06-06 12:20 UTC, Recmo commented on src/views/KYC.js
> +  <h2>KYC Page</h2>
same here

2017-06-06 12:20 UTC, Recmo commented on src/views/Login.js
> +  <h2>Login Page</h2>
and here, I won't mention it from here on.

2017-06-06 12:20 UTC, Recmo commented on src/views/ConfirmEmail.js
> +  <KYCLink>Registration succeed go to KYC page</KYCLink> <br />
Use `<p>` around text instead of using `div` or `br`. The `<br/>` tag should never be used.

2017-06-06 12:20 UTC, Recmo commented on src/views/QuotedStartups.js
> +          <td>Iconomi ICN</td>
Dummy data doesn't have to be `i18n`ed, but the table headers need to.

2017-06-06 12:21 UTC, Recmo commented on src/views/QuotedStartups.js
> +          <td>Iconomi ICN</td>
Looks good, just needs some `i18n` functions.

2017-06-06 12:22 UTC, Recmo commented
Looks good, just needs some `i18n` functions, and some `<br/>` tags to get rid of.

2017-06-06 14:13 UTC, recmo approved these changes
Let's do the `i18n` stuff later.

2017-06-06 14:15 UTC, merged